name: qnlp-tut

dependencies:
  - python=3.9
  - pip
  - pip:
    - pandas
    - torch
    - torchvision
    - pennylane==0.30.0
    - lambeq[extras]
    - jupyterlab
    - matplotlib
    - ipykernel
    - scikit-learn
    - nltk
    - gensim
    - seaborn
